// <auto-generated />
namespace Zaggie_Festa_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajuste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajuste));
        
        string IMigrationMetadata.Id
        {
            get { return "201703211927050_ajuste "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
